# helm dependency update .
# helm install infra . --namespace fluxcd --create-namespace
apiVersion: v2
name: infra
description: This chart deploy required components on my Kubernetes cluster

version: 0.1.0
appVersion: 1.10.0

dependencies:
  - name: helm-operator
    version: 1.1.0
    repository: https://charts.fluxcd.io