---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    name: traefik
    version: {{ .Values.traefik.chartVersion }}
  values:
    service:
      type: NodePort
    ports:
      web:
        port: 8080
        nodePort: 30080
        expose: true
      internal:
        port: 8888
        nodePort: 30088
        expose: true
      websecure:
        port: 4443
        nodePort: 30443
        expose: true
      traefik:
        port: 9000
        nodePort: 30090
        expose: true
    additionalArguments:
      - "--api.insecure"
      - "--certificatesresolvers.myresolver.acme.tlschallenge"
      - "--certificatesresolvers.myresolver.acme.email=re.veenhuis@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
    ingressRoute:
      dashboard:
        enabled: false

# Expose dashboard to "internal" entrypoint instead of traefik
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.traefik.ingress.entrypoints }}
  namespace: traefik
spec:
  rules:
  - host: {{ .Values.traefik.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-traefik
          servicePort: 9000