---
- hosts: all
  become: true
  tasks:

  - name: Run common tasks
    include: roles/common/tasks/main.yml

  - name: Run k8s tasks
    include: roles/k8s/tasks/main.yml

  handlers:
    - name: docker status
      service: name=docker state=started
