---
- hosts: all
  become: true
  vars:
    control_plane_endpoint: 192.168.33.3
    control_plane_endpoint_port: 8443
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - common
    - haproxy
    - k8s

  handlers:
    - name: docker status
      service: name=docker state=started
