---
- hosts: all
  become: true
  tasks:

  - name: Run main tasks
    include: roles/common/tasks/main.yml

  - name: Run master tasks
    include: roles/common/tasks/master.yml
    when: inventory_hostname == "master1"

  - name: Run node tasks
    include: roles/common/tasks/node.yml
    when: not inventory_hostname == "master1"

  - name: Run traefik tasks
    include: roles/common/tasks/traefik.yml
    when: inventory_hostname == "master1"
    become: false

  handlers:
    - name: docker status
      service: name=docker state=started