---
- hosts: all
  become: true
  vars:
    control_plane_endpoint: 10.0.33.3
    control_plane_endpoint_port: 8443
    control_plane_interface: eth1
    http_endpoint: 192.168.33.3
    http_interface: eth2
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - common
    - keepalived
    - haproxy
    - k8s
    - influxdb
  handlers:
    - name: docker status
      service: name=docker state=started
