{{- if .Values.rookCeph.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-config
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: https://github.com/pixiono/kubernetes.git
    targetRevision: HEAD
    path: charts/rook-config
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
{{- end }}
