{{- if .Values.rookCeph.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  annotations:
      argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: {{ .Values.rookCeph.chartVersion }}
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      selfHeal: false
{{- end }}
