---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  annotations:
      argocd.argoproj.io/sync-wave: "-1"

# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   name: traefik
#   namespace: traefik
# spec:
#   chart:
#     repository: https://containous.github.io/traefik-helm-chart
#     name: traefik
#     version: {{ .Values.traefik.chartVersion }}
#   values:
#     service:
#       type: NodePort
#     ports:
#       web:
#         port: 8080
#         nodePort: 30080
#         expose: true
#       internal:
#         port: 8888
#         nodePort: 30088
#         expose: true
#       websecure:
#         port: 4443
#         nodePort: 30443
#         expose: true
#       traefik:
#         port: 9000
#         nodePort: 30090
#         expose: true
#     additionalArguments:
#       - "--api.insecure"
#       - "--certificatesresolvers.myresolver.acme.tlschallenge"
#       - "--certificatesresolvers.myresolver.acme.email=re.veenhuis@gmail.com"
#       - "--certificatesresolvers.myresolver.acme.storage=acme.json"
#     ingressRoute:
#       dashboard:
#         enabled: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://containous.github.io/traefik-helm-chart
    chart: traefik
    targetRevision: {{ .Values.traefik.chartVersion }}
    helm:
      values: |
        service:
          type: NodePort
        ports:
          web:
            port: 8080
            nodePort: 30080
            expose: true
          internal:
            port: 8888
            nodePort: 30088
            expose: true
          websecure:
            port: 4443
            nodePort: 30443
            expose: true
          traefik:
            port: 9000
            nodePort: 30090
            expose: true
        additionalArguments:
          - "--api.insecure"
          - "--certificatesresolvers.myresolver.acme.tlschallenge"
          - "--certificatesresolvers.myresolver.acme.email=re.veenhuis@gmail.com"
          - "--certificatesresolvers.myresolver.acme.storage=acme.json"
        ingressRoute:
          dashboard:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: false

# Expose dashboard to "internal" entrypoint instead of traefik (Could be fixed in the future)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.traefik.ingress.entrypoints }}
  namespace: traefik
spec:
  rules:
  - host: {{ .Values.traefik.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik
          servicePort: 9000