- name: Test if Kubernetes is already Initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init

- name: Initialize the Kubernetes cluster using kubeadm
  command: "kubeadm init --control-plane-endpoint={{ control_plane_endpoint }}:{{ control_plane_endpoint_port }} --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={{ node_ip }}"
  when: not kubernetes_init.stat.exists

- include: roles/k8s/tasks/kube_config.yml

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml
