- name: Test if Kubernetes is already Initialized
  stat:
    # path: /etc/kubernetes/admin.conf
    path: /etc/kubernetes/pki/ca.crt
  register: kubernetes_init

- name: Upload certifiactes
  command: kubeadm init phase upload-certs --upload-certs
  delegate_to: "{{ groups['master'][0] }}"
  when: not kubernetes_init.stat.exists
  register: cert_key

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['master'][0] }}"
  when: not kubernetes_init.stat.exists

- name: Join node to cluster
  shell: "{{ join_command.stdout }} --apiserver-advertise-address={{ node_ip }} {% if 'master' in group_names %} --certificate-key {{ cert_key.stdout_lines[2] }} --control-plane {% endif %}"
  when: not kubernetes_init.stat.exists

- include: roles/k8s/tasks/kube_config.yml
  when: "'master' in group_names"
