apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chronograf
  namespace: monitoring
spec:
  entryPoints:
    - internal
  routes:
  - match: Host(`chronograf.local`)
    kind: Rule
    services:
    - name: chronograf-chronograf
      port: 80
