---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    type: local
    app: influxdb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/influxdb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi