- name: Create a k8s namespace
  k8s:
    name: traefik
    api_version: v1
    kind: Namespace
    state: present

- name: Upload traefik config
  copy:
    src: ../files/traefik.yml
    dest: /tmp/traefik.yml

- name: Apply traefik objects
  command: kubectl apply -f /tmp/traefik.yml -n traefik