- name: Set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: Add ssh-key
  authorized_key:
    user: vagrant
    state: present
    key: https://github.com/pixiono.keys

- name: Install common packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - ntp
    - vim
    - htop
    - tree
