- name: Set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: Install common packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - ntp
    - vim
    - htop
    - tree
