- name: Configure netowork interfaces
  template:
    src: vagrant-netplan.yaml.j2
    dest: /etc/netplan/99-vagrant-netplan.yaml
  register: netplan_config
  when: ansible_user == "vagrant"

- name: Apply netplan
  command: netplan apply
  when: netplan_config.changed and ansible_user == "vagrant"

- name: Run dns tasks
  include: roles/common/tasks/dns.yml
  tags: base
  when: ansible_user == "vagrant"

- name: Set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin
  tags: base

- name: Upgrade apt packages
  apt:
    name: "*"
    state: latest
  tags: base

- name: Install common packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - vim
    - htop
    - tree
  tags: base
