- name: Run dns tasks
  include: roles/common/tasks/dns.yml
  tags: base

- name: Set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin
  tags: base

- name: Install common packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - vim
    - htop
    - tree
  tags: base
